### ISSUE TITLE
some user problem

### ISSUE THREAD

**Issue by edwardkuo09** [luyiyun/NormAE#1]
Hi,I want to use your software,but I don’t know what is “name” in metabolomics_data,"group" and "class" in batch_information.I want to know the way how can I use this software. Thank you very much.

**Comment by luyiyun** [comment]
"name" means the name of metabolites. They may be represented by m/z and retention time (M64T32 means m/z is 64 and retention time is 32), or represented by true metabolites name (for example, Urea).


"group" in batch_information means the biological labels, for example cancer or normal tissue. It is not necessary.


"class" means the label that indicated whether it is a QC sample. In principle, it is not necessary because NormAE doesn't need QC samples. However, the existence of QC samples can be used to get more stable results.
On 7/21/2021 ***@***.***> wrote：

Hi,I want to use your software,but I don’t know what is “name” in metabolomics_data,"group" and "class" in batch_information.I want to know the way how can I use this software. Thank you very much.

**Comment by edwardkuo09** [comment]
hi,I want to use your software but I don’t know where to enter my data and use this software.Whether it is downloaded your code and input the location of my data?Thank you very much.

**Comment by luyiyun** [comment]
yes，you need download the code and install the needful modules that have been shown in the readme. Then, rename your data files and put them into the data folder. Finally, you can use NormAE by command line.






| |
荣志炜
|
|
***@***.***
|
签名由网易邮箱大师定制
On 7/26/2021 ***@***.***> wrote：

hi,I want to use your software but I don’t know where to enter my data and use this software.Whether it is downloaded your code and input the location of my data?Thank you very much.

**Comment by edwardkuo09** [comment]
hi,Whether the folder need us to create and where is the interface can I give the commend line?Thanks

**Comment by edwardkuo09** [comment]
hi,I have a problem that I don't know where I went wrong.

```
python main.py --task train --meta_data C:\Users\edwardkuo\Downloads\NormAE-release/path/to/meta.csv --sample_data C:\Users\edwardkuo\Downloads\NormAE-release/path/to/sample.information.csv --save C:\Users\edwardkuo\Downloads\NormAE-release\path\to\save_dir
```
This is the settings of training:
```
the settings of training：
task:  train
meta_data:  C:\Users\edwardkuo\Downloads\NormAE-release/path/to/meta.csv
sample_data:  C:\Users\edwardkuo\Downloads\NormAE-release/path/to/sample.information.csv
train_data:  all
save:  C:\Users\edwardkuo\Downloads\NormAE-release\path\to\save_dir
ae_encoder_units:  [1000, 1000]
ae_decoder_units:  [1000, 1000]
disc_b_units:  [250, 250]
disc_o_units:  [250, 250]
bottle_num:  500
dropouts:  (0.3, 0.1, 0.3, 0.3)
lambda_b:  1.0
lambda_o:  1.0
lr_rec:  0.0002
lr_disc_b:  0.005
lr_disc_o:  0.0005
epoch:  (1000, 10, 700)
use_batch_for_order:  True
batch_size:  64
load:  None
visdom_env:  main
visdom_port:  8097
num_workers:  12
use_log:  False
use_batch:  None
sample_size:  None
random_seed:  1234
device:  None
```

This is the error message:

```
Traceback (most recent call last):
  File "C:\Users\edwardkuo\Downloads\NormAE-release\PycharmProjects\pythonProject\.idea\inspectionProfiles\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Variable.__del__ of <tkinter.IntVar object at 0x000002427F5A5A90>>
Traceback (most recent call last):
  File "C:\Users\edwardkuo\Downloads\NormAE-release\PycharmProjects\pythonProject\.idea\inspectionProfiles\lib\tkinter\__init__.py", line 332, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x000002427F5A5FD0>>
```
